services:
  altstore-source:
    build: .
    container_name: altstore-source
    restart: unless-stopped
    ports:
      - "${ALTSTORE_PORT:-8789}:80"
      - "${ALTSTORE_HTTPS_PORT:-443}:443"
    volumes:
      - ./content:/usr/share/nginx/html:ro
      - ./letsencrypt:/etc/nginx/certs:ro
