server {
    listen 80;
    server_name _;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name _;

    ssl_certificate /etc/nginx/certs/live/8.138.233.235/fullchain.pem;
    ssl_certificate_key /etc/nginx/certs/live/8.138.233.235/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3;

    root /usr/share/nginx/html;
    default_type application/octet-stream;

    location = /apps.json {
        default_type application/json;
        add_header Cache-Control "no-store" always;
        try_files $uri =404;
    }

    location / {
        add_header Cache-Control "no-store" always;
        try_files $uri =404;
    }
}
